const mongoose = require('mongoose');

const Number = new mongoose.Schema({
    guild: String,
    parent: String,
    memberNumber: String,
    memberNumber_name: String,
    userNumber: String,
    userNumber_name: String,
    BotNumber: String,
    BotNumber_name: String,
    channelnumber: String,
    channelnumber_name: String,
    textnumber: String,
    textnumber_name: String,
    voicenumber: String,
    voicenumber_name: String,
    categoriesnumber: String,
    categoriesnumber_name: String,
    rolesnumber: String,
    rolesnumber_name: String,
    rolenumber: String,
    rolenumber_name: String,
    norolenumber: String,
    norolenumber_name: String,
    emojisnumber: String, 
    emojisnumber_name: String,
    staticnumber: String,
    staticnumber_name: String,
    gifnumber: String,
    gifnumber_name: String,
    stickersnumber:String,
    stickersnumber_name: String,
    boostsnumber: String,
    boostsnumber_name: String,
    tier: String,
    tier_name: String,
    onlinenumber: String,
    onlinenumber_name: String,
    dndnumber: String,
    dndnumber_name: String,
    idlenumber: String,
    idlenumber_name: String,
    offlinenumber: String,
    offlinenumber_name: String,
    onlinebotnumber: String,
    onlinebotnumber_name: String,
    statusnumber: String,
    statusnumber_name: String,
});

module.exports = new mongoose.model('Number', Number)